version: '3'
services:
    cgi:
        build: 
            context: ./docker
        ports:
            - $API_PORT:8080
        tty: true
        volumes:
            - ./docker/html/:/app/html/
        env_file:
            - .env
